name: Update Stock Data

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub Actions tab

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"   # Match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add processed_stock_data.csv
          git commit -m "Update stock data [skip ci]" || echo "No changes to commit"
          git push
